import { Routes } from '@angular/router';
import { requireMaster, requireSession } from './core/auth';

export const routes: Routes = [
  { path: 'login', title: 'Entrar · ZapMQ', loadComponent: () => import('./pages/login').then((m) => m.LoginPage) },
  {
    path: '',
    canActivate: [requireSession],
    loadComponent: () => import('./layout/shell').then((m) => m.Shell),
    children: [
      { path: '', pathMatch: 'full', title: 'Visão geral · ZapMQ', loadComponent: () => import('./pages/overview').then((m) => m.OverviewPage) },
      { path: 'mapa', title: 'Mapa · ZapMQ', loadComponent: () => import('./pages/map').then((m) => m.MapPage) },
      { path: 'filas', title: 'Filas · ZapMQ', loadComponent: () => import('./pages/queues').then((m) => m.QueuesPage) },
      { path: 'filas/:name/observar', title: 'Observar fila · ZapMQ', loadComponent: () => import('./pages/queue-watch').then((m) => m.QueueWatchPage) },
      { path: 'filas/:name', title: 'Fila · ZapMQ', loadComponent: () => import('./pages/queue-detail').then((m) => m.QueueDetailPage) },
      { path: 'mortas', title: 'Mensagens mortas · ZapMQ', loadComponent: () => import('./pages/dead-letters').then((m) => m.DeadLettersPage) },
      { path: 'workers', title: 'Processos e serviços · ZapMQ', loadComponent: () => import('./pages/workers').then((m) => m.WorkersPage) },
      { path: 'workers/eventos', title: 'Histórico · Worker Control', loadComponent: () => import('./pages/worker-events').then((m) => m.WorkerEventsPage) },
      { path: 'workers/configuracao', title: 'Configuração · Worker Control', loadComponent: () => import('./pages/worker-config').then((m) => m.WorkerConfigPage) },
      { path: 'workers/trace-grupo/:grupo', title: 'Trace do grupo · Worker Control', loadComponent: () => import('./pages/trace').then((m) => m.TracePage) },
      { path: 'workers/trace-servico/:servico', title: 'Trace do serviço · ZapMQ', loadComponent: () => import('./pages/trace').then((m) => m.TracePage) },
      { path: 'workers/trace/:pid', title: 'Trace · Worker Control', loadComponent: () => import('./pages/trace').then((m) => m.TracePage) },
      { path: 'trafego', title: 'Tráfego · ZapMQ', loadComponent: () => import('./pages/traffic').then((m) => m.TrafficPage) },
      { path: 'banco/alteracoes', title: 'Alterações no banco · ZapMQ', loadComponent: () => import('./pages/database-changes').then((m) => m.DatabaseChangesPage) },
      { path: 'banco/alteracoes/:id', title: 'Alteração no banco · ZapMQ', loadComponent: () => import('./pages/database-change').then((m) => m.DatabaseChangePage) },
      { path: 'banco/objetos', title: 'Objetos do banco · ZapMQ', loadComponent: () => import('./pages/database-objects').then((m) => m.DatabaseObjectsPage) },
      { path: 'banco/objetos/:database/:kind/:schema/:name', title: 'Objeto do banco · ZapMQ', loadComponent: () => import('./pages/database-object').then((m) => m.DatabaseObjectPage) },
      { path: 'banco', title: 'Banco de dados · ZapMQ', loadComponent: () => import('./pages/database').then((m) => m.DatabasePage) },
      { path: 'web', title: 'Aplicação web · ZapMQ', loadComponent: () => import('./pages/web').then((m) => m.WebPage) },
      { path: 'workers/servicos', title: 'Serviços · ZapMQ', loadComponent: () => import('./pages/services').then((m) => m.ServicesPage) },
      { path: 'workers/conexoes', title: 'Conexões · ZapMQ', loadComponent: () => import('./pages/connections').then((m) => m.ConnectionsPage) },
      { path: 'transporte', title: 'Transporte · ZapMQ', loadComponent: () => import('./pages/transport-area').then((m) => m.TransportAreaPage) },
      { path: 'transporte/pacotes', title: 'Pacotes · ZapMQ', loadComponent: () => import('./pages/transport-packages').then((m) => m.TransportPackagesPage) },
      { path: 'transporte/pacotes/:id', title: 'Pacote · ZapMQ', loadComponent: () => import('./pages/transport-package').then((m) => m.TransportPackagePage) },
      { path: 'usuarios', title: 'Usuários · ZapMQ', canActivate: [requireMaster], loadComponent: () => import('./pages/users').then((m) => m.UsersPage) },
      { path: 'aplicacoes', redirectTo: 'workers/conexoes' },
    ],
  },
  { path: '**', redirectTo: '' },
];
